name: Build React App
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Upload to S3
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./local_file.txt
          destination: s3://yourbucket/folder/local_file.txt
          aws_access_key_id: ${{ secret.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
      env:
        AWS_S3_BUCKET: kansinbeom-testapp-bucket1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: "dist"
